# Generated by Django 3.2.9 on 2021-11-04 13:41

import Doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(max_length=250, verbose_name='')),
                ('doctorTitle', models.TextField(verbose_name='Doctor Title')),
                ('phoneNumber', models.IntegerField(verbose_name='Phone Number')),
                ('speciality', models.CharField(max_length=500, verbose_name='Speciality')),
                ('blog', models.TextField(verbose_name='Blog')),
                ('image', models.FileField(upload_to=Doctor.models.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='LoaclMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineName', models.CharField(max_length=500, verbose_name='Medicine Name0')),
                ('medicineType', models.CharField(max_length=250, verbose_name='Medicine Type')),
                ('companyNem', models.CharField(max_length=500, verbose_name='Medicine Name')),
            ],
        ),
        migrations.CreateModel(
            name='LocalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=500, verbose_name='Test Name')),
                ('type', models.CharField(max_length=250, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Descriptio')),
            ],
        ),
    ]
