# Generated by Django 3.2.9 on 2021-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='doctorName',
            field=models.CharField(max_length=250, verbose_name='Doctor Name'),
        ),
    ]
