# Generated by Django 3.2.9 on 2021-11-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber_name', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patinetLimit', models.IntegerField(verbose_name='Patient Limit')),
                ('SerialLimitForOneContactNumber', models.IntegerField(verbose_name='Serlial Limit For One Contact Number')),
                ('patientAccountLimitForOneNumber', models.IntegerField(verbose_name='patient Account Limit For One Number')),
                ('indexingForLateCommer', models.IntegerField(verbose_name='Indexing For Late Commer')),
                ('indexingForReportShower', models.IntegerField(verbose_name='Indexing For Report Shower')),
                ('isSendMessage', models.BooleanField(verbose_name='is_send_message')),
                ('chember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chember_settings', to='chember.chember')),
            ],
        ),
        migrations.CreateModel(
            name='ChemberSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=500, verbose_name='Days')),
                ('startTime', models.TimeField(verbose_name='Start Time')),
                ('endTime', models.TimeField(verbose_name='End Time')),
                ('chember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chember_schedule', to='chember.chember')),
            ],
        ),
    ]
