# Generated by Django 3.2.9 on 2021-11-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chember', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemberschedule',
            name='chember',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chember_schedule', to='chember.chember'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='chember',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chember_settings', to='chember.chember'),
        ),
    ]
