# Generated by Django 3.2.9 on 2021-11-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chember', '0002_auto_20211106_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemberschedule',
            name='day',
            field=models.CharField(max_length=500, null=True, verbose_name='Days'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='SerialLimitForOneContactNumber',
            field=models.IntegerField(default=0, verbose_name='Serlial Limit For One Contact Number'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='indexingForLateCommer',
            field=models.IntegerField(default=0, verbose_name='Indexing For Late Commer'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='indexingForReportShower',
            field=models.IntegerField(default=0, verbose_name='Indexing For Report Shower'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='isSendMessage',
            field=models.BooleanField(default=False, verbose_name='is_send_message'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='patientAccountLimitForOneNumber',
            field=models.IntegerField(default=0, verbose_name='patient Account Limit For One Number'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='patinetLimit',
            field=models.IntegerField(default=0, verbose_name='Patient Limit'),
        ),
    ]
