# Generated by Django 3.2.9 on 2021-11-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chember', '0004_auto_20211106_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemberschedule',
            name='chember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chember_schedule', to='chember.chember'),
        ),
    ]
